PHPOffice/PHPWord

src/PhpWord/TemplateProcessor.php
Some modification request for #614
=>  Template processor setValue() improvements #614 

src/PhpWord/Element/Image.php
if there are many images in document are used and one of them throws `InvalidImageException` it is very difficult to detect which one without any message here...
=> Add info about Invalid image

docs/elements.rst, src/PhpWord/Element/Image.php, tests/PhpWord/Element/ImageTest.php
This change allows us to create an PhpOffice\PhpWord\Element\Image from a string representing the image data.
```php
$source = file_get_contents(__DIR__ . '/../_files/images/earth.jpg');
$image = new Image($source);
```
Of course in real life `$source` would come from a DB for instance.
Thanks to this you do not have to write the image data to file before passing it to the constructor.
This solves issue #921
=> add support for Image creation from string image data

src/PhpWord/Writer/Word2007/Part/Settings.php, tests/PhpWord/Writer/Word2007/Part/SettingsTest.php
The test works because the warning is only raised once `$phpWord->getCompatibility()->getOoxmlVersion()` is no longer null.
=> Fixes PHPOffice/PHPWord#927

src/PhpWord/Style/Paper.php, src/PhpWord/Style/Section.php, tests/PhpWord/Style/PaperTest.php, tests/PhpWord/Style/SectionTest.php
fix for issue #976 
I opted for the call to the Convertor as I'm not for duplicating code :-)
=> fix paper size and add tests for Paper class

samples/Sample_13_Images.php, src/PhpWord/Element/Image.php, tests/PhpWord/Element/ImageTest.php
this fixes issue #983 
As images are now loaded using file_get_contents, it is possible to modify the stream context using stream_context_set_default(...).
In ImageTest I'm using 
```php
$arrContextOptions = array(
"ssl" => array(
"verify_peer" => false,
"verify_peer_name" => false,
),
);
stream_context_set_default($arrContextOptions);
```
which you should obviously not do in a production environment, instead you should pass the certificate to use to connect to the remote url:
```php
$arrContextOptions = array(
"ssl" => array(
"cafile" => "/path/to/bundle/cacert.pem",
"verify_peer" => true,
"verify_peer_name" => true,
),
);
stream_context_set_default($arrContextOptions);
```
[set thread on stackoverflow](http://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-wit …
=> fix image loading over https

docs/elements.rst, samples/Sample_06_Footnote.php, src/PhpWord/Element/Section.php, src/PhpWord/SimpleType/FootnoteProperties.php, src/PhpWord/Writer/Word2007/Part/Document.php, tests/PhpWord/SimpleType/FootnotePropertiesTest.php, tests/PhpWord/Writer/Word2007/Part/DocumentTest.php
This will allow you to use another numbering for the footnote reference.
- 1, 2, 3 (default)
- I, II, III
- i, ii, iii
- A, B, C
- ...
You can also decide to put all footnotes at 
- the end of the document
- the end of the section
- the end of the page (default)
You can also decide when to restart from 1
- continuous (default)
- each Section
- each Page
And finally you can decide not to start with 1
=> Add possibility to control the footnote number

.gitignore, docs/general.rst, src/PhpWord/Settings.php, src/PhpWord/Writer/Word2007/Part/Settings.php, tests/PhpWord/SettingsTest.php, tests/PhpWord/Writer/Word2007/Part/SettingsTest.php
This pull request allows you set hide spelling and/or grammatical errors.
Simply use it as this
```php
\PhpOffice\PhpWord\Settings::setSpellingErrorsHidden(true);
\PhpOffice\PhpWord\Settings::setGrammaticalErrorsHidden(true);
```
This corresponds to the following option in Word:
This does not fix issue #542 as I did not update the reader to read the settings.xml file.
Anyone feel free to do so :-)
=> Add possibility to show/hide spelling and grammatical errors

src/PhpWord/Element/Section.php
Sample 12 shows how to add a different header for the first page:
```
// Add first page header
$header = $section->addHeader();
$header->firstPage();
...
// Add header for all other pages
$subsequent = $section->addHeader();
```
This is supposed to work also for footers (since `Header` itself is a subclass of `Footer`), but it's currently broken because `Section::hasDifferentFirstPage()` only checks if a first-page specific header exists, but doesn't check for a first-page specific footer, too.
This PR adds the missing check, fixing the rendering of footers with type `Footer::FIRST`.
=> Fix: different footer for first page

docs/elements.rst, samples/Sample_27_Field.php, src/PhpWord/Element/AbstractContainer.php, src/PhpWord/Element/Field.php, src/PhpWord/Writer/Word2007/Element/Field.php, tests/PhpWord/Element/FieldTest.php, tests/PhpWord/Writer/Word2007/ElementTest.php
Added support for XE and INDEX fields in PhpOffice\PhpWord\Element\Field.
Here is the documentation about those fields:
[XE (Index Entry) field](https://support.office.com/en-us/article/Field-codes-XE-Index-Entry-field-abaf7c78-6e21-418d-bf8b-f8186d2e4d08?ui=en-US&rs=en-US&ad=US)
[Index field](https://support.office.com/en-us/article/Field-codes-Index-field-adafcf4a-cb30-43f6-85c7-743da1635d9e?ui=en-US&rs=en-US&ad=US)
=> Add support for XE and INDEX fields

src/PhpWord/Writer/Word2007/Style/Frame.php
This is a fix for https://github.com/PHPOffice/PHPWord/issues/489
In 64bit OS, `PHP_INT_MAX = 9223372036854775807`, and it seems to be too big for MicrosoftWord XML to handle.
Enforce the max value to `2147483647`, which is the value of PHP_INT_MAX of 32 bit OS.
=> 489: Fix z-index size too big in 64bit OS

src/PhpWord/Element/AbstractContainer.php
Suppressing the PHP warning doesn't seem to work. Padding the $args array does.
=> pad the $args array instead of ignoring errors

CHANGELOG.md, src/PhpWord/Shared/Html.php
This is a continuation of PR #416 which appears to have been abandoned by @twmobius. The commits herein are just the same commits that he submitted, but I have addressed the concerns raised by @Progi1984 in [this comment](https://github.com/PHPOffice/PHPWord/pull/416#issuecomment-66249254).
This PR should resolve #257 and #324.
=> Resolves certain HTML tags rendering no output

CHANGELOG.md, docs/elements.rst, docs/general.rst, samples/Sample_17_TitleTOC.php, src/PhpWord/Metadata/Settings.php, src/PhpWord/Writer/Word2007/Part/Settings.php, src/PhpWord/Writer/Word2007/Style/Font.php, tests/PhpWord/Metadata/SettingsTest.php
When setting the updateFields to true Word will request to update the fields when opening the document.
Fixes #951
=> Allow to force an update of all fields on opening a document

src/PhpWord/Element/AbstractContainer.php
This fixes exception if you want to put checkbox inside textrun which is inside a table cell. See code above.
``` php
$table = $section->addTable();
$table->addRow();
$cell = $table->addCell(2000);
$textRun = $cell->addTextRun();
$textRun->addCheckBox('test', ' yes');
$textRun->addCheckBox('test', ' no');
```
=> Add TextRun as container for CheckBox

src/PhpWord/Writer/Word2007/Element/FormField.php
Pad any empty dropdown entries we find so that xmlWriter doesn't
generate an error.  Fix for issue #583.
=> Fix Empty Dropdown Entry

CHANGELOG.md, README.md, composer.json, samples/Sample_26_Html.php, samples/Sample_Header.php, src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
This pull request provides 2 improvements
- parsing of the `align` HTML attribute
- showing the source code when running the samples in a browser
Fixes #1230 #895
=> Parse html align attribute

CHANGELOG.md, docs/elements.rst, docs/general.rst, docs/installing.rst, src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Reader/Word2007/Settings.php, src/PhpWord/Reader/Word2007/Styles.php, src/PhpWord/Style/Paragraph.php, src/PhpWord/Writer/Word2007/Element/Shape.php, src/PhpWord/Writer/Word2007/Part/Styles.php, src/PhpWord/Writer/Word2007/Style/Paragraph.php
Word2007 reader was not reading default document font name and size.
Fixes #1235
=> fix reading of docx default style

CHANGELOG.md, README.md, docs/elements.rst, samples/Sample_26_Html.php, src/PhpWord/Element/AbstractContainer.php, src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
As a follow up of #1215 and #945: The current fix swallows texts in formatted lists when list item does not contain solely text formatted all the same.
This fix renders all texts.
#945 
Edit: I modified tests because it shows another issue that is not part of this fix
Running `compooser check` leads to
`Script ./vendor/bin/php-cs-fixer fix --ansi --dry-run --diff handling the check event returned with error code 8`
=> Parse formatting inside HTML lists

samples/Sample_26_Html.php, src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
Add parsing of `<a href="">`
Fixes #1255
=> Add parsing of HTML links

tests/PhpWord/Shared/HtmlTest.php
Minor typo in Test introduced in #1239
- [x ] I have run `composer check` and no errors were reported
=> fix typo in test method name

src/PhpWord/Element/Image.php, src/PhpWord/Writer/AbstractWriter.php
PNG images downloaded from remote sources can be either blurry or, worse, very glitched. This is because [`imagesavealpha($image, true)`](http://php.net/manual/en/function.imagesavealpha.php) is not run automatically when PNG images are downloaded, created, and saved locally for file creation.
RE: #667
=> Save PNG alpha information when using remote images.

CHANGELOG.md, src/PhpWord/Reader/Word2007/AbstractPart.php, tests/PhpWord/Reader/Word2007/ElementTest.php, tests/PhpWord/_includes/AbstractTestReader.php
When loading an existing word document, textbreaks are not being parsed
Fixes #1274
=> Fix parsing of textbreaks

composer.json, src/PhpWord/TemplateProcessor.php
Fixes https://github.com/PHPOffice/PHPWord/issues/1256
=> Remove zend-stdlib dependency

docs/containers.rst, docs/elements.rst, docs/general.rst, docs/styles.rst
The unit *twip* should be written in a consitent style.
=> Use consistent name for twip unit

src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
This fix the style parsing process when style is empty.
`list($a, $b) = $c` throw a notice if `$c` contain less than 2 entries.
=> Fix HTML parsing when style attribute is empty

src/PhpWord/Writer/Word2007/Part/Settings.php, tests/PhpWord/Writer/Word2007/Part/SettingsTest.php
According to http://www.datypic.com/sc/ooxml/t-w_ST_OnOff.html valid values for `w:ST_OnOff` are:
- true/false (<- the pair I chose)
- on/off
- 0/1
=> Improve attribute value of On/Off type

composer.json
Windows does not like the "./" syntax. It should also be fine according to https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands
=> Make Composer scripts compatible with Windows

src/PhpWord/Style/Language.php
Added support to Brazilian Portuguese laungague. Because it's necessary to verify orthography the right language.
=> Added new constant to Brazilian portuguese language

CHANGELOG.md, docs/styles.rst, samples/Sample_13_Images.php, src/PhpWord/Style/Frame.php, src/PhpWord/Writer/Word2007/Style/Frame.php, tests/PhpWord/Style/FontTest.php, tests/PhpWord/Style/ImageTest.php, tests/PhpWord/Writer/HTML/ElementTest.php, tests/PhpWord/Writer/Word2007/Style/ImageTest.php
Add support for Text wrapping distance around images
=> add text wrapping distance

src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Writer/HTML/Element/Title.php, src/PhpWord/Writer/ODText/Element/Title.php, src/PhpWord/Writer/RTF/Element/Text.php, tests/PhpWord/Reader/Word2007/ElementTest.php, tests/PhpWord/Reader/Word2007/StyleTest.php, tests/PhpWord/Writer/Word2007Test.php
Adds support for Word2007 reader to understand <w:tab/> element in <w:r>. All samples seen so far had only either w:tab or w:t elements. Encoded as "\t" character. This will still display correctly in MS Word, however a proper writer should also be implemented.
Related to #862 .
=> Add support for reading <w:tab/> element in runs.

src/PhpWord/Element/Field.php
- Fixed a typo: d-M-yyy -> d-M-yyyy
- Fixed the casing on the hours to be correct for two formats. (Hours can be either "HH" or "h", but "H" is invalid.)
- Expanded the list of valid date formats, mostly to add support for Month-Day-Year formats, but also added several new Day-Month-Year formats as well.
Here's the output from my Word document when I tested each of the formats below.  (Output is arranged in the order in which the array elements are specified):
```
8/6/2015
2015-08-06
2015-08
Aug-15
Aug-2015
1:19 PM
1:19:40 PM
13:19
13:19:40
Thursday 6 August 2015
6 August 2015
6-Aug-15
6 Aug. 15
6-8-15
6-8-15 1:19
6-8-15 1:19:40
6-8-15 1:19 PM
6-8-15 1:19:40 PM
6-8-15 13:19
6-8-15 13:19:40
6/8/15
6/8/15 1:19
6/8/15 1:19:40
6/8/15 1:19 PM
6/8/15 1:19:40 PM
6/8/15 13:19
6/8/15 13:19:40 …
```
=> Fix Dateformat typo, fix hours casing, add Month-Day-Year formats

CHANGELOG.md, src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
Add parsing of line-height and text-indent  CSS when reading HTML
Fixes #1204
=> add parsing of line-height and text-indent

CHANGELOG.md, samples/Sample_09_Tables.php, src/PhpWord/Writer/HTML/Element/Table.php, tests/PhpWord/Writer/HTML/ElementTest.php
Adds support for rowspan and colspan in the HTML Writer. The GridSpan and VMerge cell styles were previously being ignored.
Fixes #1283 for documents created at runtime. A fix for #1291 is still required when reading a saved document with <w:vMerge> tags that don't have 'w:val="continue"' attributes.
=> Fix colspan and rowspan for tables in HTML Writer

samples/Sample_32_Chart.php, src/PhpWord/Style/Chart.php, src/PhpWord/Writer/Word2007/Part/Chart.php
Added options 'showAxisLabels', 'showGridX', 'showGridY' to charts style element.
Added appropriet set and get methods.
Those options can be testet in Sample_32_Charts.php, but they are set to false for now.
Default output of that sample is not changed.
=> Added the ability to enable gridlines and axislabels on charts

docs/elements.rst, src/PhpWord/Shared/Html.php
The `addImage` API is not well designed from a security standpoint. Passing user data to `addImage` in the assumption that only an image is added fails when a malicious user uploads a file path instead of an image file and leads to arbitrary file reads. This commit adds a corresponding warning to the RST documentation.
Furthermore a similar warning to `Html::addHtml` is added, as `Html::parseImage` passes the `<img>` `value` attribute to the `Image` constructor, thus suffering from the same issue. As the `Html` class seems not to be covered by the documentation the documentation was not updated.
Note that "reading arbitrary files" might be limited to image files, however I did not look into this further.
=> Improve security-related documentation of addImage and addHtml

CHANGELOG.md, docs/elements.rst, docs/styles.rst
According to the change in https://github.com/PHPOffice/PHPWord/pull/874 the unit now is `pt`.
=> Wrong unit in image style documentation

src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
This add support for internal link on Html::addHTML method
should fix #1300
=> support internal link in addHtml method

CHANGELOG.md, docs/styles.rst, src/PhpWord/ComplexType/TblWidth.php, src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Style/Table.php, src/PhpWord/Writer/Word2007/Style/Table.php, tests/PhpWord/Reader/Word2007/StyleTest.php, tests/PhpWord/Style/TableTest.php, tests/PhpWord/Writer/Word2007/Style/TableTest.php
This adds support for table indent (http://www.datypic.com/sc/ooxml/e-w_tblInd-1.html)
=> Add support for table indent

samples/Sample_07_TemplateCloneRow.php, samples/Sample_23_TemplateBlock.php
This method call required both an array of writes and the filename, which was
missing in two method calls.
---
I could not really check the last two items on the checklist since they are not really relevant.
=> Fix calls to the getEndingNotes method in the samples

.travis.yml, composer.json, src/PhpWord/Element/AbstractElement.php, src/PhpWord/PhpWord.php, src/PhpWord/Style.php, src/PhpWord/Style/Font.php
Methods `addFontStyle`, `addParagraphStyle`, `addLinkStyle`, `addNumberingStyle`, `addTitleStyle`, and `setDefaultParagraphStyle` does allow `\PhpOffice\PhpWord\Style\AbstractStyle` to be passed as `Style::setStyleValues` checks for this on line 193.
=> Update documentation for Style::add*Style methods

composer.json
`ext-zip` seems to be required for development, but isn't specified in `composer.json`.
```
There were 2 failures:
1) PhpOffice\PhpWord\TemplateProcessorTest::testXslStyleSheetCanNotBeAppliedOnFailureOfSettingParameterValue
Failed asserting that exception of type "Error" matches expected exception "\PhpOffice\PhpWord\Exception\Exception". Message was: "Class 'ZipArchive' not found" at
/home/jonathan/Workspace/PHPWord/src/PhpWord/Shared/ZipArchive.php:134
/home/jonathan/Workspace/PHPWord/src/PhpWord/TemplateProcessor.php:88
/home/jonathan/Workspace/PHPWord/tests/PhpWord/TemplateProcessorTest.php:122
.
2) PhpOffice\PhpWord\TemplateProcessorTest::testXslStyleSheetCanNotBeAppliedOnFailureOfLoadingXmlFromTemplate
Failed asserting that exception of type "Error" matches expected exception …
```
=> Require `ext-zip` for development

CHANGELOG.md, composer.json, phpunit.xml.dist, src/PhpWord/Shared/Html.php, src/PhpWord/TemplateProcessor.php, tests/PhpWord/_includes/XmlDocument.php
XXE injection possible when parsing XML
Fixes #1421 by @Tom4t0
=> disable entity loader before parsing XML to avoid XXE injection

src/PhpWord/Writer/HTML/Element/Title.php, tests/PhpWord/Writer/HTML/ElementTest.php
When the text content of a Title is a TextRun, the writer is losing the text, returning a empty `<h1>`.
Fixes #1435
=> HTML Title Writer loses text when Title contains a TextRun instead a string.

src/PhpWord/Writer/Word2007/Element/Image.php, src/PhpWord/Writer/Word2007/Style/Frame.php
Writer / Word2007 / Style / Frame / write(): now support vertical align (skipped property)
Writer / Word2007 / Element / Image / writeWatermark(): now support insert without paragraph, similar to writeImage()
=> writer / word2007 / support valign and watermark without paragraph

docs/styles.rst
Improve documentation add hints for class constants
=> [Doc] add/align possible values from class constant

.travis.yml, CHANGELOG.md, src/PhpWord/Writer/RTF/Style/Section.php
When output as RTF the decimal places of pagesize are coming out at the start of the document. See https://stackoverflow.com/questions/48391201/numbers-show-at-beginning-of-phpword-document
This only changes it for RTF writer
=> RTF writer: Round getPageSizeW and getPageSizeH to avoid decimals

.travis.yml, CHANGELOG.md, src/PhpWord/Reader/Word2007.php
When loading some documents from Sharepoint, I got notices and warnings about non-existent keys. By skipping those keys, the problem seems to be resolved.
Fixes these messages:
```
PHP Notice:  Undefined index: document in /home/stefan/Projects/garrcomm/PHPWord/src/PhpWord/Reader/Word2007.php on line 65
PHP Warning:  Invalid argument supplied for foreach() in /home/stefan/Projects/garrcomm/PHPWord/src/PhpWord/Reader/Word2007.php on line 65
```
- [n/a] The new code is covered by unit tests (check build/coverage for coverage report)
- [n/a] I have update the documentation to describe the changes
=> Fix loading of Sharepoint document

tests/PhpWord/Writer/HTML/ElementTest.php
Using dedicated PHPUnit assertions, we can get better error messages when debugging errors, for example:
```diff
-$this->assertTrue($xpath->query('/html/body/p[1]/ins')->length == 1); // Failing asserting that true is false
+$this->assertEquals(1, $xpath->query('/html/body/p[1]/ins')->length); // Failing asserting that variables is equal to 1
```
Fixes: -
=> Use dedicated PHPUnit assertions

src/PhpWord/TemplateProcessor.php
the method is `protected`,
but since it is called with `self` instead of `static`
it does not allow for subclasses to override it
(we have a special case of mostly ISO-8859-1 strings sometimes containing MS Word apostrophes,
and these appear as question marks in the document when `utf8_encode` is used,
but are displayed fine when we use `mb_convert_encoding($string, 'UTF-8', 'windows-1252')`)
An alternative would be to make the `ensureUtf8Encoded` non static,
since it only appears to be used in a non static method.
=> allow to override TemplateProcessor#ensureUtf8Encoded

src/PhpWord/Reader/Word2007/AbstractPart.php
If link target doesn't exist, still add the text anyway. 
This has fixed issues for me with broken anchors. If the anchor is broken it just doesn't even create an element in the list and so text is lost. Even if the anchor is broken the content should still be there. 
I can write, or attempt to write a unit test for this if this change makes sense. 
=> [WIP] Still add text if link missing

CHANGELOG.md, src/PhpWord/Element/SDT.php, src/PhpWord/Writer/Word2007/Element/SDT.php, tests/PhpWord/Element/SDTTest.php, tests/PhpWord/Writer/Word2007/ElementTest.php
The specification for SDTs (Structured Document Tags) allows for these types:
- plain text
- rich text
- date picker
- combo box
- drop-down list
- image
Only date, combo box and drop-down list were previously implemented.
I have added the **plain text** type.
=> Add "Plain Text" type to SDT (Structured Document Tags)

CHANGELOG.md, src/PhpWord/Writer/RTF/Style/Border.php, src/PhpWord/Writer/RTF/Style/Font.php, src/PhpWord/Writer/RTF/Style/Indentation.php, src/PhpWord/Writer/RTF/Style/Paragraph.php, src/PhpWord/Writer/RTF/Style/Section.php, src/PhpWord/Writer/RTF/Style/Tab.php
In #1493 fix, only page dimensions where rounded for RTF writers. But every numerical value should be rounded, as per the spec([v1.5](http://www.biblioscape.com/rtf15_spec.htm#Heading2), more recent versions say the same) :
> The delimiter marks the end of an RTF control word, and can be one of the following : [...]
> * A digit or a hyphen (-), which indicates that a numeric parameter follows. The subsequent digital sequence is then delimited by a space or any character other than a letter or a digit.
This PR fixes that by rounding every numerical values used in formatting RTF documents (I hope i did not forget any value ...).
- [-] The new code is covered by unit tests (check build/coverage for coverage report) (no new code)
- [-] I have updated the documentation to describe the changes …
=> For RTF writers, sizes should should never have decimals

src/PhpWord/Reader/Word2007/Styles.php, tests/PhpWord/Reader/Word2007/StyleTest.php
Depending on the language of the word installation, the styleId is different.
e.g.
- en: Heading1
- fr: Titre1
- pt: Titulo1
- de: Übershrift1
- ...
Because of this the parser fails to parse the Styles
The solution is to use the `<w:name />` instead
Fixes #1431
=> Style Name Parsing fails if document generated by a non-english word version

CHANGELOG.md, docs/styles.rst, samples/Sample_36_RTL.php, samples/index.php, src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Style/Table.php, src/PhpWord/Writer/ODText/Style/Paragraph.php, src/PhpWord/Writer/ODText/Style/Table.php, src/PhpWord/Writer/Word2007/Style/Table.php, tests/PhpWord/Reader/Word2007/StyleTest.php, tests/PhpWord/Writer/Word2007/Style/TableTest.php
Table should be presentable in RTL mode.
This adds support for http://www.datypic.com/sc/ooxml/e-w_bidiVisual-1.html
Fixes #1549
=> Add RightToLeft table presentation

src/PhpWord/Style/Language.php
libreoffice uses zxx as default language code. This PR updates the language code validation to accept this code.
Fixes #1298
=> Language::validateLocale should pass with locale 'zxx'.

CHANGELOG.md, docs/styles.rst, samples/Sample_03_Sections.php, src/PhpWord/Reader/Word2007/Document.php, src/PhpWord/SimpleType/VerticalJc.php, src/PhpWord/Style/Cell.php, src/PhpWord/Style/Section.php, src/PhpWord/Writer/Word2007/Style/Section.php, tests/PhpWord/Reader/Word2007/StyleTest.php, tests/PhpWord/Style/CellTest.php, tests/PhpWord/Style/SectionTest.php
Add support for section vertical text alignment
http://www.datypic.com/sc/ooxml/e-w_vAlign-1.html
Fixes #672
=> implement support for section vAlign

CHANGELOG.md, samples/Sample_26_Html.php, src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
Parsing of CSS border-style
Fixes #1551
=> fix parsing of border-color and add test

src/PhpWord/Element/TrackChange.php, tests/PhpWord/Element/TrackChangeTest.php
DateTime::createFromFormat(...) returns either a \DateTime instance or FALSE, not NULL.  Working on the basis that there might be legitimate TrackChange constructor calls containing a NULL date parameter, line 67 has been expanded to check not only for NOT NULL but also NOT FALSE.
Without this additional check, a document with "Track Changes" enabled could cause an Exception to be raised when loaded into a reader.
"Exception: DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character"
I couldn't see any relevant documentation that would benefit from being updated with details of this change, hence the incomplete checklist.
Fixes # N/A
=> TrackChange doesn't handle all return types of \DateTime::createFromFormat(...)

src/PhpWord/Shared/Html.php
No linked issue.
When you want to extends PhpOffice\PhpWord\Shared\Html class, the protected method **parseNode**,  will call "self::parseChildNodes" making the call parseNode useless in the new class. And prevent parseChildNodes from being customized in the new class.
The change made allows the **parseNode** method to look for **parseChildNodes** first in the newly created class
More concretely, you can now customize **parseChildNodes** by extending the Html class
Maybe we can do same thing with all static methods (replacing calls _self::_ by _static::_)
=> call static instead of self on protected method

README.md
I went in to check the updated CONTRIBUTING file and noticed the link in the README directs users to CONTRIBUTING.md on the master branch. I've updated that link and one other to use relative links so they'll always link to the current branch (and will be more portable).
=> Use relative links in README to ensure they go to the correct branch

src/PhpWord/Element/AbstractContainer.php, tests/PhpWord/Element/CellTest.php
if we use PreserveText inside table or special characters, issue fixed
Relavent
https://stackoverflow.com/questions/33070424/phpword-cannot-add-preservetext-in-section
=> To support PreserveText inside sub container

src/PhpWord/Writer/Word2007/Element/ListItemRun.php, tests/PhpWord/Writer/Word2007/ElementTest.php
This commit fixes issue #1529
This commit prevents nested w:pPr elements when using a ListItemRun with
a paragraph style. The different between a ListItem and a ListItem run
is that the setWithoutPPR method is called on the ParagraphStyleWriter
(PhpOffice\PhpWord\Writer\Word2007\Style\Paragraph).
According to the specs it's not allowed to have nested w:pPr elements.
See http://www.datypic.com/sc/ooxml/e-w_pPr-2.html
=> No nested w:pPr elements in ListItemRun.

src/PhpWord/Style/ListItem.php
By allowing to set the numId in the ListItem style manually, you can separate lists. Every ListItem with the same numId belongs to one list. This allows you to restart list counting. For example:
addListItem("tem 1", 0, ['listType' => 7, 'numId' => 1]);
addListItem("tem 2", 0, ['listType' => 7, 'numId' => 1]);
addListItem("tem 3", 0, ['listType' => 7, 'numId' => 1]);
// restart list
addListItem("item 1", 0, ['listType' => 7, 'numId' => 2]);
addListItem("tem 2", 0, ['listType' => 7, 'numId' => 2]);
addListItem("tem 3", 0, ['listType' => 7, 'numId' => 2]);
=> Adding setNumId method for ListItem style

.travis.yml
Fixes the crash when calling `apt-get update` in PHP 5.3 environment in Travis CI. Since the culprit is a 3rd party repo for MongoDB and that we don't need MongoDB, I just remove the repo definition so `apt-get` doesn't try to connect to it.
Fixes #1706
=> Fix apt-get crash in Travis CI for PHP 5.3

src/PhpWord/Element/AbstractElement.php
There was return type currently missing. Also property type was wrong as `$parent` can be null (i.e. for `Section`)
=> Added return type

src/PhpWord/Writer/RTF/Element/Field.php, tests/PhpWord/Writer/RTF/ElementTest.php
Add support for PAGE, NUMPAGES and DATE fields in RTF documents.
- (pointless) I have updated the documentation to describe the changes
=> Add support for basic fields in RTF writer.

tests/PhpWord/_includes/AbstractWebServerEmbeddedTest.php
When tests are run with a recent version of PHP, `\Symfony\Component\Process\Process` called in `AbstractWebServerEmbeddedTest` needs to be passed an array. When tests are run in an old PHP version (like 5.4), it needs to be passed a string.
Tests should pass regardless of the supported PHP version is running them.
Make sure that we use `\Symfony\Component\Process\Process::fromShellCommandLine()` if available. If it's not available, it means we are running an older version of `Process` where it's safe to pass a string to the constructor.
Fixes #1770
=> Fix PHPUnit tests on develop branch

docs/styles.rst, src/PhpWord/Style/Paragraph.php
As stated in #358, the documentation about `indent` and `hanging` styling for the Paragraph element is wrong:
- It states that the values for ``indent`` and ``hanging`` are in twips while they are in half-inches
- It does not mention the ``indentation`` property which allows setting values in twips and the ``firstLine`` and ``right`` indentations as well.
Fixes #358
=> fix: documentation about paragraph indentation

docs/templates-processing.rst
Adding save() and saveAs() methods docs
Adding save() and saveAs() methods docs
=> Update templates processing docs

src/PhpWord/Escaper/Rtf.php, tests/PhpWord/Escaper/RtfEscaper2Test.php, tests/PhpWord/Writer/RTF/ElementTest.php
1. Codes meant to be in hex are specified in decimal.
Consequently characters which don't need escaping are escaped.
2. Special handling (prepend backslash) needed for {, }, and \.
RTF docs generated with those characters cannot be opened in Word.
3. Tab character needs to be escaped as \tab.
RTF docs drop these characters.
While running test suite, found that Writer/RTF/ElementTest was coded
only for Unix line endings, and fails on Windows. Changed so that it
would work on either.
=> Improvements in RTF writer

src/PhpWord/Writer/HTML/Element/ListItemRun.php, tests/PhpWord/Writer/HTML/ElementTest.php
Add List for docx to html. Implemented ListItemRun for HTML in Writer.
Fixes List item fail #1717 (issue)
=> Add support for ListItemRun in HTML writer

docs/elements.rst, src/PhpWord/Element/Section.php, src/PhpWord/Writer/Word2007/Part/Document.php
- Fixed documentation about FootnoteProperties which contained an invalid code snippet, so that people can actually use the code:
- it now uses the correct class names
- no more typo in variable name usage
- now uses a Footnote position parameter that works when outputting Word (`POSITION_BENEATH_TEXT`). `POSITION_DOC_END` only works for Endnotes.
- Fixed bogus method name `$section->addFootnotePropoperties()`:
- added a method with the correct spelling `$section->addFootnoteProperties()`
- former method still works but is marked as deprecated
- migrated code to use the correct method name
=> Fix documentation and method name for FootnoteProperties

docs/elements.rst, src/PhpWord/Element/Field.php, src/PhpWord/Writer/Word2007/Element/Field.php, src/PhpWord/Writer/Word2007/Style/Font.php, tests/PhpWord/Writer/Word2007/ElementTest.php, tests/PhpWord/Writer/Word2007/Style/FontTest.php, tests/PhpWord/_includes/AbstractWebServerEmbeddedTest.php
=> Add font style for Field elements

src/PhpWord/Shared/Converter.php, src/PhpWord/Writer/RTF/Element/AbstractElement.php, src/PhpWord/Writer/RTF/Element/Table.php, src/PhpWord/Writer/RTF/Element/TextRun.php, src/PhpWord/Writer/RTF/Element/Title.php, src/PhpWord/Writer/RTF/Part/Document.php, src/PhpWord/Writer/RTF/Style/Font.php, src/PhpWord/Writer/RTF/Style/Paragraph.php, src/PhpWord/Writer/RTF/Style/Section.php, tests/PhpWord/Shared/ConverterTest.php, tests/PhpWord/Writer/RTF/ElementTest.php, tests/PhpWord/Writer/RTF/HeaderFooterTest.php, tests/PhpWord/Writer/RTF/StyleTest.php, tests/PhpWord/_includes/AbstractWebServerEmbeddedTest.php
RTF Changes
1. Converter is currently expecting colors as strings of hex digits,
but PhpWord allows specification of colors by named constant, so
result is random when one of those is used. This change handles
all the named colors.
2. Table needs \pard at end; formatting may be wrong without it.
3. RTF writer will no longer ignore paragraph style for TextRun.
4. RTF writer will no longer ignore paragraph and font style for Title.
5. Add support for RTF headers and footers.
6. Add support for right-to-left in font.
7. Add support for PageBreakBefore and LineHeight for paragraphs.
8. Add support for PageNumberingStart for sections.
There are test cases for all of these changes.
No documentation changes required.
=> Add support for several features for the RTF writer

src/PhpWord/Reader/Word2007/AbstractPart.php
Some online converters (e.g. CloudConvert) add images with different path than `Office 2011`.
If embed element not found I try to find element with different path
=> Added support for "cloudConvert" images

src/PhpWord/Shared/Converter.php
Fixes PHPDoc `@param` and `@return` types for several `Converter` methods:
* Some methods supposedly expect an `int`, even though `float` values make sense.
* Some methods supposedly return a `float`, even though they return an `int`.
([Psalm](https://psalm.dev/) noticed these inconsistencies for me.)
=> Fixes PHPDoc @param and @return types for several Converter methods

.scrutinizer.yml, .travis.yml, README.md, composer.json, docs/installing.rst, phpmd.xml.dist, src/PhpWord/Element/AbstractContainer.php, src/PhpWord/Element/Image.php, src/PhpWord/Reader/MsDoc.php, src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Shared/Converter.php, src/PhpWord/Shared/Html.php, src/PhpWord/TemplateProcessor.php, src/PhpWord/Writer/HTML/Element/AbstractElement.php, src/PhpWord/Writer/HTML/Part/AbstractPart.php, tests/PhpWord/Element/TableTest.php, tests/PhpWord/TemplateProcessorTest.php, tests/PhpWord/Writer/PDF/TCPDFTest.php, tests/PhpWord/_includes/XmlDocument.php
- compatibility with PHP 7.4
- compatibility with PHP 8.0 (for full support require update in 3rd libraries)
- travis-ci: fixed execution on PHP 5.x
- fixed scrutinizer, allow zip extension
- migrate from abandoned `Zend\Escaper` to `Laminas Escaper`
For full compatibility with php 8.0 require PR https://github.com/PHPOffice/Common/pull/34
Fixes https://github.com/PHPOffice/PHPWord/issues/1944
Fixes https://github.com/PHPOffice/PHPWord/issues/1874
Fixes https://github.com/PHPOffice/PHPWord/issues/1797
=> Compatibility with PHP 7.4, PHP 8.0 and migrate to Laminas Escaper

docs/templates-processing.rst
fix typo in doc
Before:  
`$templateProcessor->cloneRowAndSetValues('userId', );`
After:  
`$templateProcessor->cloneRowAndSetValues('userId', $values);`
=> Fix typo in docs. Update templates-processing.rst

src/PhpWord/Element/Field.php, src/PhpWord/Element/Section.php, src/PhpWord/Shared/Converter.php, src/PhpWord/Style/Paragraph.php, src/PhpWord/Writer/ODText/Element/Field.php, src/PhpWord/Writer/ODText/Element/Image.php, src/PhpWord/Writer/ODText/Element/Link.php, src/PhpWord/Writer/ODText/Element/PageBreak.php, src/PhpWord/Writer/ODText/Element/Text.php, src/PhpWord/Writer/ODText/Element/TextRun.php, src/PhpWord/Writer/ODText/Element/Title.php, src/PhpWord/Writer/ODText/Part/Content.php, src/PhpWord/Writer/ODText/Part/Styles.php, src/PhpWord/Writer/ODText/Style/Font.php, src/PhpWord/Writer/ODText/Style/Paragraph.php, tests/PhpWord/Element/ImageTest.php, tests/PhpWord/Shared/ConverterTest.php, tests/PhpWord/Writer/ODText/Element/ImageTest.php, tests/PhpWord/Writer/ODText/ElementTest.php, tests/PhpWord/Writer/ODText/Part/AbstractPartTest.php, tests/PhpWord/Writer/ODText/Part/ContentTest.php, tests/PhpWord/Writer/ODText/Style/FontTest.php, tests/PhpWord/Writer/ODText/Style/ParagraphTest.php, tests/PhpWord/Writer/ODText/Style/SectionTest.php, tests/PhpWord/_includes/TestHelperDOCX.php, tests/PhpWord/_includes/XmlDocument.php
Implement a number of features implemented in PhpWord,
but not yet supported in PhpWord ODT Writer.
1. Add default file to tests/PhpWord/_includes/XmlDocument.php to make it
considerably easier to test ODT changes (and Word2007 changes involving
files other that document.xml).
2. Page break before each section.
3. Page numbering start.
4. Font style for Headings.
5. Alignment for images.
6. Paragraph style for TextRun.
7. "Hide grammatical errors" for whole document.
8. Page layout for each section.
9. For each page layout, support user-specified page width, page height,
orientation, margin top, margin bottom, margin left, margin right.
10. Page header and footer.
11. Named colors.
12. NoProof font style.
13. Paragraph Style - spaceBefore, spaceAfter, lineHeight, pageBreakBefore, …
=> ODT Changes

src/PhpWord/Writer/PDF/TCPDF.php
Sometimes we need create TCPDF object with modified initial arguments.
This change allow rewrite only createExternalWriterInstance() in user defined TCPDF class.
=> Allow to redefine TCPDF object

src/PhpWord/TemplateProcessor.php
Recently I've updated to libreoffice 7.x and noticed weird bug, by default ms word and libreoffice 6.x and below show no line, but starting from libreoffice 7.x border appeared around images which was inserted using `setImageValue`
MsWord
Libreoffice 7.x
=> Fix image stroke in libreoffice 7.x

src/PhpWord/Element/AbstractContainer.php, src/PhpWord/Writer/PDF/DomPDF.php, src/PhpWord/Writer/PDF/MPDF.php, src/PhpWord/Writer/PDF/TCPDF.php
Allow to use customized PDF library without rewriting save() method.
Customized PDF libray sample: https://tcpdf.org/examples/example_003/
Similar to PhpSpreadsheet merged PR (https://github.com/PHPOffice/PhpSpreadsheet/pull/266)
=> allow to use customized pdf library

docs/templates-processing.rst
Added a fix for missing parameter to the cloneRowAndSetValues function call in its example.
=> Fix example for cloneRowAndSetValues

src/PhpWord/Writer/Word2007/Style/AbstractStyle.php, tests/PhpWord/Writer/Word2007/Element/ChartTest.php, tests/PhpWord/Writer/Word2007/Element/FormFieldTest.php, tests/PhpWord/Writer/Word2007/ElementTest.php, tests/PhpWord/Writer/Word2007/Part/SettingsTest.php, tests/PhpWord/Writer/Word2007/Style/ImageTest.php, tests/PhpWord/Writer/Word2007/Style/SectionTest.php, tests/PhpWord/_includes/AbstractWebServerEmbeddedTest.php, tests/PhpWord/_includes/TestHelperDOCX.php, tests/PhpWord/_includes/XmlDocument.php
After this change, Writer/Word2007 is 100% covered.
One source change is required. Writer/Word2007/Style/AbstractStyle
has incorrectly searched Measurement Array using
in_array (which searches values) rather than array_key_exists (keys).
There was no test for this, and now there is.
3 changes in tests/PhpWord/_includes are borrowed from "ODT Changes"
(pull request 1796, not yet merged)
and "Fix PHPUnit Tests" (pull request 1771,
merged after work on this change was started).
Writer/Word2007/ElementTest was becoming too unwieldy. Tests for
Chart and FormFields were moved to their own members.
=> Improve Word2007 Test Coverage

docs/general.rst, phpword.ini.dist, src/PhpWord/Settings.php, src/PhpWord/Style/Section.php, tests/PhpWord/SettingsTest.php, tests/PhpWord/_includes/AbstractWebServerEmbeddedTest.php
Each section currently has a hard-coded default paper of A4.
It would make sense to allow the user to set this default,
and specify it in a configuration file, just as is done
with default font name and size.
=> Make Default Paper Configurable

src/PhpWord/TemplateProcessor.php
Fix when setComplexValue is not found in the template.
=> Add null check when setComplexValue is not found

docs/templates-processing.rst, src/PhpWord/TemplateProcessor.php, tests/PhpWord/TemplateProcessorTest.php
This PR adds support to supply a closure to the `setImageValue` call on the `TemplateProcessor` class. 
Usage case: we generate serveral documents based from templates and supply a set of replacement tags. One of these tags contains a image that's generated on the fly which results in a performance impact. We must generate this image on every document as we aren't sure if the template contains the replacement tag in question. 
This ensures the generation only happens when the tag is found and the `TemplateProcesser` want's to inject the image.
_Ran the test suite but was unable to run the php-cs script due to what i think are filemode issues on Bash on Windows (the CS script wanted to change all files)._
=> Allow a closure to be passed with image replacement tags

src/PhpWord/TemplateProcessor.php
=> fix image limit

src/PhpWord/TemplateProcessor.php, tests/PhpWord/_includes/AbstractWebServerEmbeddedTest.php
I was met with the issue reported in #1750 and fixed it. 
The problem was that the regexp to clone and add number did include the size attributes in the tag before the number. So I added a second capture group so that image attributes are properly placed after the tag with it's added number.
I also fixed the call to Process to use an array as it otherwise cause hundred of errors as it now expects an array instead of a string.
All tests are passed and code coverage is unchanged.
Fixes #1750 #1624
=> TemplateProcessor cloneBlock wrongly clones images

src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
Currently importing HTML via `PhpWord\Shared\Html::addHtml()` has couple of bugs and misses support for some at least basic HTML tags & attributes. This PR attempts to fix these issues without BC break (at least no existing unit test break):
* fix [passing](https://github.com/PHPOffice/PHPWord/blob/develop/src/PhpWord/Shared/Html.php#L364) `width` property into cells, allowing also to control colum widths inside tables. Following would currently not work `style="width: 35%"` - because width is passed as a wrong argument. Once fixed, it will also allow to control columns width inside tables. Since all widths are currently ignored (not recognized) they are set to `width = "auto"`.
* fix unit conversion for margins/spacing - instead of converting to …
=> Enhancements to addHTML parser

samples/Sample_09_Tables.php
Columns are hardcoded in the basic table loop instead of using the predefined $rows and $cols variables
Columns are hardcoded in the basic table loop instead of using the predefined $rows and $cols variables
- [ x ] I have run `composer run-script check --timeout=0` and no errors were reported
- [ x ] The new code is covered by unit tests (check build/coverage for coverage report)
- [ x ] I have updated the documentation to describe the changes
=> Unused variables $rows, $cols

src/PhpWord/Style/Language.php
Some documents come with style locale as en_GB, en_US this fixes these locale codes
Fixes #
replaces "_" to "-"
- [x ] I have run `composer run-script check --timeout=0` and no errors were reported
- [ x] The new code is covered by unit tests (check build/coverage for coverage report)
=> Some document have non-standard locale code

src/PhpWord/TemplateProcessor.php
Reference Issue:   #1800 
Update from this PR: https://github.com/PHPOffice/PHPWord/pull/1801
When you have multiple Blocks in multiple Rows, some of blocks cannot be replaced
Only the last block was replaced.
This because some word file will drop-line after `xml` tag, and the regular expression engine in different versions cannot find the matched block.
File: `TemplateProcessor.php`
Line: 740
Change the regexp pattern to: 
```php
'/(.*((?s)<w:p\b(?:(?!<w:p\b).)*?\${' . $blockname . '}<\/w:.*?p>))(.*)((?s)<w:p\b(?:(?!<w:p\b).)[^$]*?\${\/' . $blockname . '}<\/w:.*?p>)/is',
```
Describe: 
- Do not find for xml.
- Start find the `<w:p` tag that closest to the blockname.
- This `<w:p` does not contain any other `<w:p` inside it.
All Done
=> Update the regexp to avoid catastrophic backtracking

src/PhpWord/Element/AbstractContainer.php, src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
The aim is to get the output closer to the source html.
I noticed the issue in the doc file generated from HTML, in the table, a border was applied to the text inside the cells. Which was not right because no border was applied to the span. I understood that [CSS inheritance of style properties](https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance) was not taken into account by the parser so I decided to implement it.
=> feat: Update addHtml to handle style inheritance

src/PhpWord/Style/Chart.php, src/PhpWord/Writer/Word2007/Part/Chart.php
Currently thechart legend position cannot be altered via an option. This release fixes that by adding in an option in getStyle to set the legend position. It's using the ISO standards for adding it.
=> Add Option for Dynamic Chart Legend Position

src/PhpWord/SimpleType/Border.php, src/PhpWord/Style/Border.php, src/PhpWord/Writer/Word2007/Style/Paragraph.php
In the [issue#294](https://github.com/PHPOffice/PHPWord/issues/294) problem, it is found that a piece of code is applied, but the disadvantage is that the border style setting is not added when setting the border, so the code of adding paragraph style is supplemented. And added a list of static constants for border styles.
=> add/setting page element border style.

composer.json
This commit fixes the BC break introduced by #1946 where it was stated
that phpword replaces package laminas/laminas-zendframework-bridge which
is not the case. Package laminas/laminas-zendframework-bridge only was
replaced from phpword.
Fixes #2028 (issue)
=> Fix BC break in #1946. This package does not replace laminas/laminas-zendframework-bridge

src/PhpWord/Writer/Word2007/Element/Image.php
Recently I switched LibreOffice from version 6 to 7 for my docx documents and noticed that a border appeared around all images that I add by using addImage. This fixes the problem by adding an attribute 'stroked' with a value 'f' to the v:shape element in Word2007 Image Element Writer. This resolves #2031.
MS Word:
LibreOffice 7:
solves #2031
=> Fix image border in Word2007 Writer for LibreOffice 7

src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
For acept text in line-height how "line-height:normal", etc.
=> Update Html parser to accept line-height:normal

src/PhpWord/Writer/Word2007/Part/Chart.php
when bar or column grouping by clustered have c:overlap,the bar will be overlap
=> Update chart, don't write 'c:overlap' if grouping is 'clustered'

docs/general.rst
The docs referenced the wrong namespace for the Language class. This happens in General usage > Document settings > Document Language.
It refers to ``PhpOffice\PhpWord\ComplexType\Language``, but there's no Language class in the namespace ``PhpOffice\PhpWord\ComplexType``. I searched in the tests to figure out where the Language class has moved to and found in ``PhpOffice\PhpWord\Writer\Word2007\Part\SettingsTest::testLanguage()`` this had to be ``PhpOffice\PhpWord\Style\Language``.
- [n/a] I have run `composer run-script check --timeout=0` and no errors were reported
- [n/a] The new code is covered by unit tests (check build/coverage for coverage report)
- [n/a] I have updated the documentation to describe the changes
=> Corrected namespace for Language class in docs.

src/PhpWord/TemplateProcessor.php
Occasionally we would have a document fail to add the images and upon further research I discovered the RID generate for the image duplicated an existing RID which caused the images to not appear in the document and some version of Word to complain the document is corrupt. The fix takes the current generation method and checks for if it already exists and simple increments the number until it finds one that doesn't exist.
potentially 1964 and 1947 and others
=> when adding image to relationship first check that the generated RID is actually unique

docs/styles.rst
Add BorderStyle for Cell Style  to documentation.
Fixes # 2089
=> Add BorderStyle for Cell Style to documentation

src/PhpWord/Shared/Html.php
HTML Reader : Heading in Text Run is not allowed
=> HTML Reader : Heading in Text Run is not allowed

src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
HTML Reader : Style page-break-after in paragraph
Thanks [SITER](https://siter.fr/)
=> HTML Reader : Style page-break-after in paragraph

src/PhpWord/Shared/Html.php, tests/PhpWord/Shared/HtmlTest.php
HTML Reader : Use `border` attribute for tables
=> HTML Reader : Use `border` attribute for tables

src/PhpWord/Element/PreserveText.php, src/PhpWord/Shared/XMLWriter.php
Fixes two issues with deprecation warnings in PHP 8.1. 
The check script fails with an error in an unrelated file, so I'm guessing that's ok: 
`/application/repos/PHPWord/src/PhpWord/Element/TOC.php:27  CamelCasePropertyName  The property $TOCStyle is not named in camelCase.`
All unit tests still pass on PHP 7.3.
=> PHP 8.1 compatability fix for PreserveText and XMLWriter

src/PhpWord/Style/Language.php
This fixes an issue in PHP8.1 where passing a NULL value to strlen() function is deprecated
=> PHP8.1 Fix issue with passing NULL value for locale into string function

.github/workflows/ci.yml, README.md, composer.json, docs/faq.rst, docs/installing.rst, phpunit.xml.dist, samples/index.php, src/PhpWord/Element/Image.php, src/PhpWord/Escaper/Xml.php, src/PhpWord/Shared/PCLZip/pclzip.lib.php, tests/PhpWord/Writer/PDF/TCPDFTest.php, tests/PhpWord/_includes/AbstractWebServerEmbeddedTest.php
This is according to our formal, published, policy to only support
eol PHP after 6 months within PHPOffice organisation.
See https://phpspreadsheet.readthedocs.io/en/latest/#php-version-support
=> Drop PHP 7.3 and older

composer.json
I found out that the homepage link on packagist.org points to: http://phpoffice.github.io/ but that site doesn't exist. So this PR updates the link to the documentation site.
=> Update homepage in composer.json

src/PhpWord/TemplateProcessor.php
Recently we had to run the template processor 80.000 times, during this processor the /tmp partition become full. After a short investigation we found a lot of files with PhpWord in theire name.
Adding a destrucutor wich clean up the tmp files seems to work.
=> [TemplateProcessor] Clean up temp files

.gitignore, src/PhpWord/Shared/Html.php, tests/PhpWordTests/Shared/HtmlTest.php
HTML Reader : Override inline style on HTML attribute for table
=> HTML Reader : Override inline style on HTML attribute for table

.github/workflows/ci.yml, composer.json, tests/PhpWordTests/Shared/HtmlTest.php, tests/PhpWordTests/Writer/Word2007/Part/DocumentTest.php
=> Support for PHP7.1 (min.)

composer.json
Instead, we've been using Scrutinizer for a while
=> Drop obsolete coverall references

src/PhpWord/Shared/Css.php, src/PhpWord/Shared/Html.php, tests/PhpWordTests/Shared/CssTest.php, tests/PhpWordTests/Shared/HtmlTest.php
HTML Reader : Add basic support for CSS Style Tag
Fixes #1375
=> HTML Reader : Add basic support for CSS Style Tag

src/PhpWord/Shared/Html.php, tests/PhpWordTests/Shared/HtmlTest.php
HTML Reader : Set style name from the CSS class
=> HTML Reader : Set style name from the CSS class

src/PhpWord/TemplateProcessor.php
The `tempDocumentHeaders` and `tempDocumentFooters` array attributes are passed to this method parameter
=> Improve TemplateProcessor#setValueForPart parameter phpdoc

src/PhpWord/Shared/Html.php
HTML Reader : Set style name from the CSS class (and if not CSS is loaded)
=> HTML Reader : Set style name from the CSS class (and if not CSS is loaded)

.github/workflows/ci.yml, composer.json
Otherwise, `composer check` and `composer fix` are broken and contributing because much harder than it should be. Also using the same version everywhere is a benefit to get consistent result locally and on CI.
=> Use local install of friendsofphp/php-cs-fixer

src/PhpWord/Reader/Word2007/AbstractPart.php
In MS Word 2021 docx files save with empty w:val of w:vMerge when expected value "continue".
I made suggest a solution:
In method readStyleDefs for argument styleDefs add fifth parameter "default value". This will allow default values to be passed for empty attributes. For example in a cells
The problem is described here: https://github.com/PHPOffice/PHPWord/issues/2330
=> Read empty vmerge

src/PhpWord/Style/Cell.php
The setWidth method did not change the width in the style, seems to be a small mistake.
Now the width is correctly for the Cell Style.
I did not create a separate issue for this.
_not applicable I would say_
_not applicable I would say_
=> Fixed setting width of Cell Style

docs/general.rst
classes not found and missing dollar sign
=> fixed code example

src/PhpWord/Style/TextBox.php, src/PhpWord/Writer/Word2007/Element/TextBox.php, src/PhpWord/Writer/Word2007/Style/TextBox.php, tests/PhpWordTests/Style/TextBoxTest.php, tests/PhpWordTests/Writer/Word2007/Part/DocumentTest.php
It is now possible to fill the background color of text box elements (only Word2007 writer!). There is no documentation for the Textbox element, so I can't add the changes.
No bugfix.
=> Add background color support for text box element for Word writer

src/PhpWord/Settings.php, src/PhpWord/Style/TextBox.php, src/PhpWord/Writer/Word2007/Element/TextBox.php, src/PhpWord/Writer/Word2007/Style/TextBox.php, tests/PhpWordTests/SettingsTest.php, tests/PhpWordTests/Style/TextBoxTest.php, tests/PhpWordTests/Writer/Word2007/Part/DocumentTest.php
Word supports fractional font sizes like 8.5pt, but PHPWord doesn't.
That fractional font size ist not supported as default font size, while font style elements support fractional font size.
=> Add support for fractional font sizes

.github/workflows/ci.yml, .gitignore, composer.json, composer.lock
We must have `composer.lock` as part of our repository. Otherwise, the tools used for development change and break things unexpectedly.
Currently, this is the case with PHPUnit 10 that introduces quite a few breaking changes. We cannot `composer install` and hope that we will get a set of compatible dependencies. Instead, we must lock our tools and upgrade them only when we want/need to upgrade them specifically, in a dedicated commit, and not part of a totally unrelated work, because it just so happenned that PHPUnit released something.
`composer.lock` is based on the oldest PHP version that is officially supported by PHP core. Currently, that is 8.0. This typically gives us compatibility out of the box for 8.0, 8.1 and 8.2 with a single lock file.
EOL PHP versions, that we unfortunately …
=> Lock all dependencies

src/PhpWord/Element/Image.php, src/PhpWord/Media.php, src/PhpWord/Writer/AbstractWriter.php, tests/PhpWordTests/Element/ImageTest.php
This sets the quality of JPEG and PNG files to their maximum. It does this by:
- defining a property called `$imageQuality` and a method called `getImageQuality()` to PhpOffice\PhpWord\Element\Image;
- setting the property `$imageQuality` to `100` in case of image/jpeg or image/jpg and set it to `0` in case of image/png;
- PhpOffice\PhpWord\Media and PhpOffice\PhpWord\Writer\AbstractWriter making use of the 'imageQuality' property.
I also added test coverage for PhpOffice\PhpWord\Element\Image::getImageQuality().
Fixes #2317
=> Use highest quality for JPEG and PNG images

src/PhpWord/Writer/Word2007.php, tests/PhpWordTests/Writer/Word2007Test.php
This PR seeks to resolve #1753, allowing files created by the word2007 writer to be detected as word files and not `application/octet-stream`. I ran into this issue while working on file upload using Laravel's build-in file validation.
Based on [this magic file](https://github.com/file/file/blob/50713f02b46825baf243bc5ae0a167f2b2b323f1/magic/Magdir/msooxml), I've deduced how the word file mimetype is detected.
The file needs to be a zip, inside the first two filenames need to match a regex, then the 3rd and 4th filenames are inspected to see what path they start with. When either matches `word/` the file is determined to be a word 2007 file.  
Before this process would find _docProps/_, which does pass the regex, but not match an office mimetype, causing the file to get the type MSOOXML …
=> Fix wrong mimetype for docx files

src/PhpWord/Reader/Word2007/AbstractPart.php
PHPWord is ignoring hyperlinks in headings.
In src\PhpWord\Reader\Word2007\AbstractPart.php only w:r elements are read.
Fixes #1792
=> Hotfix: In headings hyperlinks are ignored. Added w:hyperlink to xpath filter

src/PhpWord/Shared/PCLZip/pclzip.lib.php
The php function strtr doesn't support empty strings as replacement. To delete a character str_replace is required.
=> Bug fix: strtr using empty string

src/PhpWord/Reader/MsDoc.php, src/PhpWord/Shared/OLERead.php
Since PHP 8.2 release Access to an undefined property into an object raise deprecated
=>  Fix PHP 8.2 deprecated about Allow access to an undefined property

CHANGELOG.md, src/PhpWord/TemplateProcessor.php
When Set Value Image into Float value, regex cant find dot character.
Initial PR : #2415 by @gdevilbat
=> TemplateProcessor : Fixed choose dimention for Float Value

CHANGELOG.md, src/PhpWord/Reader/AbstractReader.php, src/PhpWord/Reader/Word2007.php, src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Style/Language.php, tests/PhpWordTests/Reader/Word2007Test.php
Word2007 Reader : Added option to disable loading images
Based on PR #2369 by @aelliott1485
=> Word2007 Reader : Added option to disable loading images

CHANGELOG.md, src/PhpWord/Writer/HTML/Part/Head.php
Added border-spacing to default styles in HTML Writer
Based on PR #2335 by @kernusr
=> HTML Writer : Added border-spacing to default styles for table

.github/workflows/ci.yml, CHANGELOG.md, README.md, phpunit.xml.dist
=> Added coveralls.io

.github/workflows/ci.yml, CHANGELOG.md
Added support for PHP 8.2 & 8.3
=> Added support for PHP 8.2 & 8.3

CHANGELOG.md, src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Style/Border.php, src/PhpWord/Style/Section.php, tests/PhpWordTests/Reader/Word2007/StyleTest.php
Add reading borders and margins for table cell in Word2007 reader.
About borders: http://www.datypic.com/sc/ooxml/e-w_tcBorders-1.html
About margins: http://www.datypic.com/sc/ooxml/e-w_tcMar-1.html
Based on PR #2351 by @kernusr
=> Word2007 Reader : Support for table cell borders and margins

docs/changes/1.x/1.2.0.md, docs/usage/writers.md, phpstan-baseline.neon, src/PhpWord/Settings.php, src/PhpWord/Writer/PDF/AbstractRenderer.php, src/PhpWord/Writer/PDF/DomPDF.php, src/PhpWord/Writer/PDF/MPDF.php, src/PhpWord/Writer/PDF/TCPDF.php, tests/PhpWordTests/SettingsTest.php, tests/PhpWordTests/Writer/PDF/DomPDFTest.php, tests/PhpWordTests/Writer/PDF/MPDFTest.php, tests/PhpWordTests/Writer/PDF/TCPDFTest.php
PDF Writer : Add config for defining the default font
Based on PR #2262 by @MikeMaldini
=> PDF Writer : Add config for defining the default font

docs/changes/1.x/1.2.0.md, docs/usage/introduction.md, docs/usage/writers.md, phpstan-baseline.neon, src/PhpWord/Metadata/Settings.php, src/PhpWord/Reader/Word2007/Settings.php, src/PhpWord/Writer/Word2007/Part/Settings.php, tests/PhpWordTests/Metadata/SettingsTest.php, tests/PhpWordTests/Writer/Word2007/Part/SettingsTest.php
Word2007 Reader/Writer: Permit book-fold printing
Superseeds #2225 by @potofcoffee
=> Word2007 Reader/Writer: Permit book-fold printing

docs/changes/1.x/1.2.0.md, docs/usage/elements/title.md, src/PhpWord/Element/AbstractContainer.php, src/PhpWord/Element/Title.php, src/PhpWord/Writer/Word2007/Element/TOC.php, tests/PhpWordTests/Element/TitleTest.php, tests/PhpWordTests/Writer/Word2007/Element/TOCTest.php, tests/PhpWordTests/Writer/Word2007/Element/TitleTest.php, tests/PhpWordTests/Writer/Word2007/ElementTest.php, tests/PhpWordTests/Writer/Word2007/Part/DocumentTest.php
Word2007 Writer : Add PageNumber to TOC
Superseeds #1652 by @jet-desk
=> Word2007 Writer : Add PageNumber to TOC

docs/changes/1.x/1.2.0.md, src/PhpWord/Shared/Text.php, src/PhpWord/TemplateProcessor.php
Remove deprecated utf8_encode in PHP 8.2
Superseeds #2447 by @mhcwebdesign
=> Remove deprecated utf8_encode in PHP 8.2

docs/changes/1.x/1.2.0.md, src/PhpWord/Shared/XMLReader.php, tests/PhpWordTests/Shared/XMLReaderTest.php
=> Word2007 Reader : Fixed reading of Office365 DocX file

docs/changes/1.x/1.2.0.md, docs/usage/elements/field.md, samples/Sample_27_Field.php, src/PhpWord/Element/Field.php, src/PhpWord/Writer/ODText/Element/Field.php, src/PhpWord/Writer/RTF/Element/Field.php, src/PhpWord/Writer/Word2007/Element/Field.php, tests/PhpWordTests/Writer/ODText/Element/FieldTest.php, tests/PhpWordTests/Writer/RTF/ElementTest.php, tests/PhpWordTests/Writer/Word2007/ElementTest.php
Added field 'FILENAME' by @milkyway-git 
Superseeds #2498
=> Added field 'FILENAME'

docs/changes/1.x/1.2.0.md, src/PhpWord/Reader/Word2007/Styles.php
Word2007 Reader : Check for null on $fontDefaultStyle
Superseeds #2491 by @spatialfree
=> Word2007 Reader : Check for null on $fontDefaultStyle

docs/changes/2.x/2.0.0.md, src/PhpWord/TemplateProcessor.php, tests/PhpWordTests/TemplateProcessorTest.php
Replace line breaks with XML representation to use multi line values with TemplateProcessor.
Fixes #268 #2323 #2486
- ~[ ] I have updated the documentation to describe the changes~
=> bug: TemplateProcessor fix multiline values

docs/changes/1.x/1.2.0.md, docs/changes/2.x/2.0.0.md, src/PhpWord/TemplateProcessor.php, tests/PhpWordTests/TemplateProcessorTest.php
Replace PR #2542.
Fix #2539. Inadvertent break in TemplateProcessor behavior after #2475. Deleted temp file on destruct. It will now persist after destructor.
=> Template Processor Persist File After Destruct

tests/PhpWordTests/Element/FormulaTest.php, tests/PhpWordTests/PhpWordTest.php
PhpUnit cannot parse the `@covers` lines in FormulaTest; they result in warnings in Coverage and Deploy tests. This PR fixes them; no change log entry should be needed.
=> Invalid Annotation in Test Member

docs/changes/2.x/2.0.0.md, src/PhpWord/Shared/Microsoft/PasswordEncoder.php
Password encoder is not 32-bit safe.
Fixes #2550
=> Fix 32-bit Problem in PasswordEncoder

docs/changes/2.x/2.0.0.md, docs/usage/writers.md
When I used PHPWord to write a PDF document, recently, I followed [the relevant docs](https://github.com/PHPOffice/PHPWord/blob/master/docs/usage/writers.md#pdf) only to find that I also had to specify a PDF renderer — otherwise the operation failed.
After a bit of research to figure out what to do to specify one, I thought it only right to document what I learned in the official documentation.
=> Extend the Options section of the PDF Writer documentation

docs/changes/2.x/2.0.0.md, src/PhpWord/Shared/ZipArchive.php, tests/PhpWordTests/TemplateProcessorTest.php
A particularly perplexing problem accidentally introduced by PR #2475. Problem does not arise for Php8, and does not arise for Php7 unit tests. But, running *not* under Phpunit auspices with Php7 can cause a warning message at destructor time if the `save` function has been used. A very artificial test is introduced to test this situation.
Fixes # 2548
=> Php7 Problem with TemplateProcessor Destructor

docs/changes/2.x/2.0.0.md, src/PhpWord/TemplateProcessor.php
Replace hardcoded macro chars by the customized ones in `deleteRow()` method of `TemplateProcessor` class
=> [TYPO] Fix hardcoded macro chars in TemplateProcessor method

docs/changes/2.x/2.0.0.md, src/PhpWord/Shared/XMLReader.php, tests/PhpWordTests/Shared/XMLReaderTest.php
This prevents fatal exceptions when trying to load corrupt files or old "doc" files, allowing applications to catch the exception and fail gracefully.
Fixes # (issue) - None. I just fixed it without reporting an issue.
=> Prevented fatal errors when opening corrupt files or "doc" files

composer.json, composer.lock, docs/changes/2.x/2.0.0.md
Bump phpoffice/math from 0.1.0 to 0.2.0
Fixes #2559
* No need unit tests => it's a dependency bump
* No need documentation => no feature or documentation needed
=> Bump phpoffice/math from 0.1.0 to 0.2.0

docs/changes/2.x/2.0.0.md, docs/usage/elements/comment.md
Documentation : Updated Comment element
Fix error on comments code snippet.
Superseeds #2097 (by @laminga)
=> Documentation : Updated Comment element

docs/changes/2.x/2.0.0.md, phpstan-baseline.neon, src/PhpWord/Reader/Word2007/AbstractPart.php, tests/PhpWordTests/Reader/Word2007/ElementTest.php
PHPWord had the option to create and write FormFields (checkbox, textinput and dropdown). This pull requests add the functionality to read those fields into the PHPWord model
Fixes #2281
Superseeds #2282 by @vincentKool
=> Word2007 Reader : Support for FormFields

composer.lock, docs/changes/2.x/2.0.0.md, src/PhpWord/Shared/Html.php, tests/PhpWordTests/Shared/HtmlTest.php
HTML Reader : Read width & height attributes in points
Fixes #2589
=> HTML Reader : Read width & height attributes in points

docs/changes/2.x/2.0.0.md, src/PhpWord/TemplateProcessor.php
Template Processor : Fixed bad naming of variables
Fixes #2586
=> Template Processor : Fixed bad naming of variables

docs/changes/2.x/2.0.0.md, src/PhpWord/Style/Border.php, src/PhpWord/Writer/HTML/Element/Table.php, src/PhpWord/Writer/RTF/Element/AbstractElement.php, src/PhpWord/Writer/RTF/Element/Table.php, src/PhpWord/Writer/RTF/Part/Header.php, src/PhpWord/Writer/Word2007/Style/MarginBorder.php, tests/PhpWordTests/Writer/RTF/Element/TableTest.php, tests/PhpWordTests/Writer/RTF/Element2Test.php
RTF Writer : Support for Table Border Style
Fixes #245
Fixes #345
=> RTF Writer : Support for Table Border Style

docs/changes/1.x/1.3.0.md, src/PhpWord/Style/Font.php, src/PhpWord/Writer/Word2007/Style/Font.php, tests/PhpWordTests/Writer/Word2007/Part/DocumentTest.php
Word2007 Writer : Fixed StrikeThrough property
Superseeds #2604 by @noec764
Fixes #1693
Fixes #1722
> If a strikethrough style was added to a text element it never appeared in the resulting document.
> Indeed, the XML generated was as follows
> ```
><w:r>
>    <w:rPr>
>        <w:strike w:val="1"/>
>        <w:dstrike w:val="0"/>
>     </w:rPr>
>     <w:t xml:space="preserve">some text</w:t>
></w:r>
>```
> The statement `<w:dstrike w:val="0"/>` should not be present here
> I figure out that the test  `$style->isDoubleStrikethrough() !== null` is true if `$style->isDoubleStrikethrough() === false`
> So as a text cannot be strike and doublestrike at the same time, word2007 ignores it.
=> Word2007 Writer : Fixed StrikeThrough property

docs/changes/1.x/1.3.0.md, src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Reader/Word2007/Document.php
Word2007 Reader: Support the page break (<w:lastRenderedPageBreak/>)
Some Word2007 document are using <w:lastRenderedPageBreak/>for page break. When converting this document to PDF, it does not add page break in final PDF.
Superseeds #2573 by @stanolacko
=> Word2007 Reader: Support the page break (`<w:lastRenderedPageBreak/>`)

docs/changes/1.x/1.3.0.md, src/PhpWord/Shared/Html.php, tests/PhpWordTests/Shared/HtmlTest.php
HTML Reader : Fixed link without href
Superseeds #2280 by @asmundstavdahl
Fixes #1562
=> HTML Reader : Fixed link without href

docs/changes/1.x/1.3.0.md, samples/Sample_37_Comments.php, src/PhpWord/Collection/AbstractCollection.php, src/PhpWord/Collection/Bookmarks.php, src/PhpWord/Collection/Charts.php, src/PhpWord/Collection/Comments.php, src/PhpWord/Collection/Endnotes.php, src/PhpWord/Collection/Footnotes.php, src/PhpWord/Collection/Titles.php, src/PhpWord/Element/AbstractElement.php, src/PhpWord/Element/Comment.php, src/PhpWord/PhpWord.php, src/PhpWord/Writer/Word2007.php, src/PhpWord/Writer/Word2007/Element/AbstractElement.php, tests/PhpWordTests/Element/CommentTest.php
Word2007 Writer: Added support for multiples comment for the same text
Superseeds #2112 by @rodrigoq
Fixes #2109
=> Word2007 Writer: Added support for multiples comment for the same text

README.md, docs/changes/1.x/1.4.0.md, samples/Sample_13_Images.php, src/PhpWord/Writer/ODText/Element/Image.php, src/PhpWord/Writer/Word2007/Element/Container.php, tests/PhpWordTests/Writer/ODText/Element/ImageTest.php, tests/PhpWordTests/XmlDocument.php
Writer ODText: Support for images inside a textRun
Fixes #2240
=> Writer ODText: Support for images inside a textRun

docs/changes/1.x/1.4.0.md, src/PhpWord/Writer/HTML/Style/Table.php, tests/PhpWordTests/Writer/HTML/Element/TableTest.php
vAlign is parsed by PHPWord but the HTMLWriter does not support it yet.
~~Fixes # (issue)~~ (no related open issue found)
=> feat: Add support for vAlign styles in the HTML Writer (Table)

docs/changes/1.x/1.4.0.md, src/PhpWord/Style/Cell.php, tests/PhpWordTests/Writer/HTML/Element/TableTest.php
vAlign and vMerge are initialized as `null` until it is explicitly set. Right now, it is not possible to unset them, after it has been set once.
I've added a null-check to skip the validation, based on the default parameter value of `null`, which indicates to me that it once was intended to work like this.
I've also fixed the type-hints, which were wrong from the start.
Fixes #2673
=> fix: Allow vAlign and vMerge on Style\Cell to be set to null

docs/changes/1.x/1.4.0.md, tests/PhpWordTests/Reader/Word2007/StyleTest.php
This new test case essentially covers the changes in b457ff5f7fadf28f4d62d1fcd5b9ee3424392835.
It ensures the new behavior works as intended and doesn't break/change by accident in the future.
~~Fixes # (issue)~~ (does not apply)
=> test: Add test case for vMerge's default value of continue

composer.json
With commit [1] development dependencies have been removed
from the `composer.json`, but not from the `composer.lock`.
This indicates a inproper use of `composer` and should be
taken care in review of pull-requests. A good practice here
is to etablish a rule that composer commands needs to be
added to the commit message and the pull-request.
Other removed dependency and downgraded dependencies have
been fixed or readded meanwhile, still missing the `phpcs`
tool for the `check composer script`.
The `CONTRIBUTION.md` states to execute `composer check`
before creating a pull-request, which is literally broken
due to the missing dependency.
This change removes the php sniffer call from the check
script. Additionally, the composer scripts are enhanced
to use the same php binary used to invoke …
=> [BUGFIX] Remove invalid tool call from composer `check` script

docs/changes/1.x/1.4.0.md, src/PhpWord/Shared/Html.php, tests/PhpWordTests/Shared/HtmlTest.php
Reader HTML: Support for differents size units for table
Fixes #2384
Fixes #2701
=> Reader HTML: Support for differents size units for table

docs/changes/1.x/1.4.0.md, docs/usage/introduction.md, src/PhpWord/PhpWord.php, src/PhpWord/Settings.php, src/PhpWord/Writer/Word2007/Part/Styles.php, tests/PhpWordTests/PhpWordTest.php, tests/PhpWordTests/SettingsTest.php
Allow PHPWord to set Latin / Asian font separately
=> feat(font): add default asian font name

docs/changes/1.x/1.4.0.md, src/PhpWord/Element/AbstractContainer.php
We encountered issues with a Word document where this is a valid combination.
This fixes parsing the document properly.
Fixes #2616
Fixes #2426
=> Reader Word2007 : Support Header elements within Title elements

docs/changes/1.x/1.4.0.md, src/PhpWord/Writer/HTML/Part/Body.php, src/PhpWord/Writer/HTML/Part/Head.php, tests/PhpWordTests/Writer/HTML/FontTest.php
add Support for Default font color in Writer HTML. This expands upon #2700
=> Writer HTML: Support Default font color

docs/changes/1.x/1.4.0.md, docs/usage/elements/ruby.md, mkdocs.yml, phpstan-baseline.neon, samples/Sample_46_RubyPhoneticGuide.php, src/PhpWord/ComplexType/RubyProperties.php, src/PhpWord/Element/AbstractContainer.php, src/PhpWord/Element/Ruby.php, src/PhpWord/Element/TextRun.php, src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Shared/Html.php, src/PhpWord/Writer/HTML/Element/Ruby.php, src/PhpWord/Writer/ODText/Element/AbstractElement.php, src/PhpWord/Writer/ODText/Element/Ruby.php, src/PhpWord/Writer/ODText/Element/Text.php, src/PhpWord/Writer/RTF/Element/Ruby.php, src/PhpWord/Writer/RTF/Element/Title.php, src/PhpWord/Writer/Word2007/Element/Ruby.php, tests/PhpWordTests/ComplexType/RubyPropertiesTest.php, tests/PhpWordTests/Element/RubyTest.php, tests/PhpWordTests/Element/TextRunTest.php, tests/PhpWordTests/Reader/Word2007/ElementTest.php, tests/PhpWordTests/Shared/HtmlTest.php, tests/PhpWordTests/Writer/HTML/Element/RubyTest.php, tests/PhpWordTests/Writer/HTML/Helper.php, tests/PhpWordTests/Writer/ODText/ElementTest.php, tests/PhpWordTests/Writer/RTF/ElementTest.php, tests/PhpWordTests/Writer/Word2007/ElementTest.php
Right now, PHPWord does not support ruby text elements (phonetic guides) at all. You can see some documentation (of a sort) on this type of element here: https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.ruby?view=openxml-3.0.1 and some how-to-use [here](https://support.microsoft.com/en-us/office/add-phonetic-guides-to-east-asian-text-c03ad8e4-799b-499e-89a2-c749fc5397e8)
A ruby (phonetic guide) element allows you to do things like this:
This PR adds both reading and writing support for ruby elements to `Word2007` files. Basic text support has been checked along with Titles. Other elements may or may not be supported at this time (in other words, I didn't test literally every element with ruby); as long as the code eventually gets into `readRunChild`, the …
=> Feature: Ruby (phonetic guide) text - Word2007 Read/Write, HTML Read/Write, RTF write, ODT basic write

docs/changes/1.x/1.4.0.md, src/PhpWord/Shared/Html.php, tests/PhpWordTests/Shared/HtmlTest.php
=> Reader HTML: Support for inherit value for property line-height

docs/changes/1.x/1.4.0.md, src/PhpWord/Writer/ODText/Part/Styles.php, tests/PhpWordTests/Writer/ODText/Style/FontTest.php
Writer ODText: Support Default font color. This is continuation of #2731 #2700
Setting a default font-color is only possible, when` style:use-window-font-color` is either not set or set to false.
To see the effect of  style:use-window-font-color, see the attachments of [kde/kword bug 231659](https://bugs.kde.org/show_bug.cgi?id=231659).
The definition of this attribute can be found in the [OpenDocument Standard](https://docs.oasis-open.org/office/OpenDocument/v1.4/csd01/part3-schema/OpenDocument-v1.4-csd01-part3-schema.html#__RefHeading__1420234_253892949), where the most relevant phrase for this discussion are:
> The determination of light or dark color is implementation-defined.
> 
> ...
> 
> false: the foreground color is specified by the fo:color attribute.  
kword did …
=> Writer ODText: Support Default font color

docs/changes/1.x/1.4.0.md, src/PhpWord/Shared/Html.php, src/PhpWord/Style/Font.php, tests/PhpWordTests/Shared/HtmlTest.php
=> Reader HTML: Support font styles for h1/h6

docs/changes/1.x/1.4.0.md, src/PhpWord/Element/Link.php, src/PhpWord/Element/Text.php, src/PhpWord/Writer/HTML/Element/Text.php, tests/PhpWordTests/Writer/HTML/Element/TextTest.php
Superseeded by #2629 by @armagedon007
=> Writer HTML: Fixed null string for Text Elements

docs/changes/1.x/1.4.0.md, src/PhpWord/TemplateProcessor.php, tests/PhpWordTests/TemplateProcessorTest.php
Template Processor: Fix 0 considered as empty string
Fixes #2572
Fixes #2703
Thanks @cavasinf & @SnipsMine
=> Template Processor: Fix 0 considered as empty string

docs/changes/1.x/1.4.0.md, tests/PhpWordTests/WriteReadback/ODTextTest.php, tests/PhpWordTests/WriteReadback/Word2007Test.php
I think that currently, there are only few good tests for the reader. (see for e.g. #2700 where the reader and writer where modified, but only the writer is actually covered by a test)
Creating and adding artifacts (docx and odt) is not ideal, as they are hard to verify and will contain random other artifacts.
By dynamically creating the test-file using the writer and reading it back in with the reader, we can simply test the reader against the writer.
In general, a WYSWYG word processor is assumed to read and save files without loosing anything. For a project like PHPOffice, the focus is stronger on the writer then the reader. With this setup, it is a lot easier to work on the reader, as a test driven development purely in PHP gets enabled - the need to use a word processor for …
=> test the reader with the writer

docs/changes/1.x/1.4.0.md, docs/usage/styles/paragraph.md, src/PhpWord/Reader/Word2007/AbstractPart.php, src/PhpWord/Style/Indentation.php, src/PhpWord/Style/Paragraph.php, src/PhpWord/Writer/Word2007/Style/Indentation.php, tests/PhpWordTests/Element/AbstractElementTest.php, tests/PhpWordTests/Reader/Word2007/StyleTest.php, tests/PhpWordTests/Style/AbstractStyleTest.php, tests/PhpWordTests/Style/IndentationTest.php, tests/PhpWordTests/Writer/EPub3/Part/AbstractPartTest.php, tests/PhpWordTests/Writer/EPub3/Style/AbstractStyleTest.php, tests/PhpWordTests/Writer/ODText/Part/AbstractPartTest.php, tests/PhpWordTests/Writer/Word2007/Part/AbstractPartTest.php, tests/PhpWordTests/Writer/Word2007/Style/IndentationTest.php
Writer/Reader Word2007: Added support for the firstLineChars for Indentation
Superseeds #2667 by @liuzhilinux
=> Writer/Reader Word2007: Added support for the firstLineChars for Indentation

composer.json, docs/changes/1.x/1.4.0.md
Release 0.3.0 has a security fix in it...
https://github.com/PHPOffice/Math/compare/0.2.0...master
=> Update phpmath from 0.2.0 to 0.3.0
