PHPOffice/PHPWord

- docs/styles.rst
> Update DOC: Added note about direction of text inside a cell

- src/PhpWord/Writer/HTML/Element/Image.php
Related with https://github.com/PHPOffice/PHPWord/issues/431#issuecomment-194815644
> Images are not being printed in PDF

- src/PhpWord/Settings.php
- src/PhpWord/Writer/Word2007/Part/Settings.php
- tests/PhpWord/SettingsTest.php
- tests/PhpWord/Writer/Word2007/Part/SettingsTest.php
> add possibility to write w:evenAndOddHeaders in settings.xml

- samples/Sample_06_Footnote.php
- src/PhpWord/ComplexType/FootnoteProperties.php
- src/PhpWord/Element/Section.php
- src/PhpWord/Shared/AbstractEnum.php
- src/PhpWord/SimpleType/NumberFormat.php
- src/PhpWord/Style/NumberingLevel.php
- src/PhpWord/Writer/Word2007/Part/Document.php
- tests/PhpWord/ComplexType/FootnotePropertiesTest.php
- tests/PhpWord/Writer/Word2007/Part/DocumentTest.php
- tests/PhpWord/Writer/Word2007/Part/NumberingTest.php
> add new NumberFormat values and refactor FootnoteProperties to use same values

- .travis.yml
- CHANGELOG.md
- README.md
- composer.json
- docs/elements.rst
Fix travis build to run on precise
Update the changelog
> do not fix dependency to old ZF version

- src/PhpWord/Writer/ODText/Style/Paragraph.php
> Fix division by zero

- src/PhpWord/Shared/OLERead.php
- src/PhpWord/Shared/PCLZip/pclzip.lib.php
I've removed the `else`s when we have already returned something :put_litter_in_its_place:
> Clean elses

- CHANGELOG.md
- src/PhpWord/Writer/HTML/Element/Bookmark.php
- tests/PhpWord/Writer/HTML/ElementTest.php
- tests/PhpWord/Writer/HTMLTest.php
Add writer for Bookmarks in HTML output
Fixes #1263
> Add HTML writer for Bookmarks + tests

- src/PhpWord/Writer/Word2007/Element/Container.php
`in_array` already return `true` or `false`.
Fixes: -
> Refactoring

- samples/Sample_Header.php
Fixes https://travis-ci.org/PHPOffice/PHPWord/jobs/364515902
> Add missing param annotation

- src/PhpWord/Style/Language.php
A simple update that add it-IT 1040 locale to Language.php
> Added Italian to supported languages

- .travis.yml
- CHANGELOG.md
- src/PhpWord/Style/Language.php
- tests/PhpWord/Style/LanguageTest.php
> Allow passing short lang code

- docs/containers.rst
Add documentation for enabling evenAndOddHeaders
Fixes #1475
> Add documentation for enabling evenAndOddHeaders

- src/PhpWord/Style/Language.php
Adds the Dutch language to the Language file.
> Added Dutch (nl-NL)

- docs/elements.rst
- samples/Sample_14_ListItem.php
Completing documentation and samples about better understanding of ListItemRun.
Fixes #1538
> Update documentation on usage of ListItemRun

- src/PhpWord/TemplateProcessor.php
See warning at http://php.net/manual/en/control-structures.foreach.php
> Break the references in foreach within TemplateProcessor

- src/PhpWord/Style/Language.php
Added new constant to Russian language.
> Added new constant to russian language

- src/PhpWord/Element/AbstractContainer.php
Update Wrong addChart definition in Abstract container class
- [ x] I have run `composer run-script check --timeout=0` and no errors were reported
> Update Wrong definition

- README.md
Fix a typo in a link
Fixes # (none)
> Fix link anchor

- tests/PhpWord/MediaTest.php
> Improve unit test

- .github/support.yml
- .github/workflows/ci.yml
- .github/workflows/github-pages.yml
Replace travis with github workflow
> add git workflow

- src/PhpWord/Escaper/Xml.php
- src/PhpWord/TemplateProcessor.php
> Php 8.1 fix #2290

- src/PhpWord/Reader/Word2007/AbstractPart.php
Add softhyphen symbol support for word reader.
> Add softhyphen support to Word2007 Reader

- src/PhpWord/Style/Language.php
Microsoft knows the variations for DE, FR and IT in Switzerland.
3 language codes added:
Add FR_CH
Add DE_CH
Add IT_CH 
https://learn.microsoft.com/en-us/previous-versions/tn-archive/cc287874(v=office.12)
> Update Language.php  FR_CH, DE_CH & IT_CH

- docs/elements.rst
Replaces table sample in list item with the better suited list item sample.
> docs: Better suited sample for list item
